### ISSUE TITLE
Building static binaries with Dune

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml-ppx/ppx_deriving#189]
I'm working on a BuckleScript-compatible port, and part of that involves shipping pre-built binaries of the ppx-transformer to npm.

The [README says](https://github.com/ocaml-ppx/ppx_deriving/blob/34b9d4b9b0e342ec0e6d0302e34cae174574792f/README.md#building-ppx-drivers):

> ... it is possible to precompile a ppx rewriter executable that includes several deriving plugins:
>
> ```sh
> ocamlfind opt -predicates ppx_driver -package ppx_deriving_foo -package ppx_deriving_bar \
>                 -package ppx_deriving.main -linkpkg -linkall -o ppx_driver
> ```

I can build the standard, dynlink'd ppx_deriving via Dune in my local opam switch, but I'm having no luck with `ocamlfind`-based building like this. Has the above-described process changed since the swap to Dune? I'm afraid I'm unfamiliar with the legacy `ocamlfind`/`ocamlbuild` approach to OCaml build-systems — all of my experience is post-jbuilder; so these tools are unfamiliar to me.

My errors are always along the lines of “ocamlfind: Package 'ppx_deriving_std' not found”; I've tried a few different names (`ppx_deriving_std`, `ppx_deriving.std` because I'm not clear on when the dotted vs. underscored names are appropriate; directly referencing `ppx_deriving.show` ...)

Reproducing exactly what I've tried:

```sh
$ git clone https://github.com/ocaml-ppx/ppx_deriving.git && cd ppx_derivingi
$ opam switch create  --with-test ./ "ocaml-base-compiler.4.06.1"
$ dune runtest # works
$ ocamlfind opt -predicates ppx_driver -package ppx_deriving.std \
>               -package ppx_deriving.main -linkpkg -linkall -o ppx_driver # fails:
ocamlfind: Package `ppx_deriving.main' not found
```

**Comment by rgrinberg** [comment]
If you're shipping pre built binaries, there's no need for ppx_deriving. You should just build a driver with all your preprocessors using dune and publish the binary that dune produces. This process should work for ppx_deriving.show, etc.

**Comment by ELLIOTTCABLE** [comment]
Hm.

1. I'm not quite clear on how that pertains to the original question — are you saying the snippet in the README *is* definitely out-of-date / non-functinal now? Let's write replacement instructions using Dune, in that case!

2. On that note, I've spent some time poring over the Dune docs, but I'm not seeing a way to build and link against a ppx-driver into a binary target; only ways to declare that a library *is* a ppx rewriter, or to declare ppx-rewriters to build into a driver *for* a library or package.

   Does this mean the only way forward is to make a dummy-file, add a Dune entry targeting that file, and tell it to preprocess the file with ppx_deriving and the `std` packages … then, I suppose, awk over Dune's output looking for a location where it's built and stored the rewriter it built to process that file? That's such a mess, there must be a better way we can describe!

**Comment by diml** [comment]
What you can do is the following: declare a public library with `(kind ppx_rewriter)` that depends on the ppx rewriters you want to distribute:

```scheme
(library
 (public_name myppx)
 (libraries ppx_deriving_foo ppx_deriving_bar))
```

 Then run `dune build --profile release` and your ready to ship ppx will be available at `_build/install/default/lib/myppx/ppx`. This binary will be suitable for passing to the `-ppx` option of the compiler.

This part is not documented as it is only meant for backward compatibility. I.e. to make ppx rewriters built dune usable from projects building with `ocamlfind`.

> Reproducing exactly what I've tried:

It seems to me that the issue is a missing a `dune build && dune install` just before the ocamlfind command. `ocamlfind` can only see libraries that have been installed on the system. If you don't want to do the installation, you can also do the following:

```
$ dune build
$ dune exec -- ocamlfind ...
```

and dune will give ocamlfind an environment in which it looks like the package has been installed. Isn't that nice? :)

**Comment by gasche** [comment]
A side-note: I realize that the ppx_deriving README is not up-to-date with respect to a world where `dune` is the default build system used by most people (describing ocamlfind usage is still nice, but it should come second, and the `myocamlbuild.ml` part could probably be dropped), but I haven't taken the time to work on this yet. Any PRs to refresh the build documentation is welcome.

It would also be nice to mention the packaging convention, for plugin authors, around `.runtime` sub-packages (your plugin should probably have one, depending on `ppx_deriving.runtime`, so that plugin users don't need to).
