### ISSUE TITLE
[proposal] ppx_deriving 5.0 and 5.1

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml-ppx/ppx_deriving#233]
OCaml 4.12 just entered its freezing period. Last release we decided to wait a bit to release ppx_deriving with ppxlib support (aka ppx_deriving 5.0) to leave people some time to adjust to the new interface.

This time I would encourage to release it as soon as possible as-is (without https://github.com/ocaml-ppx/ppx_deriving/pull/231), so that people get some incentive to get up-to-date then release ppx_deriving 5.1 which would include https://github.com/ocaml-ppx/ppx_deriving/pull/231.
This way packages down the line that still require ppxlib < 0.16.0 can still be compatible with some versions of ppx_deriving 5.x, this would increase quick adoption somewhat.

@gasche @thierry-martinez I can handle the release if you don't have the time.

**Comment by gasche** [comment]
Your plan sounds good to me and, yes, for me it would be very useful if you could handle the release. Thanks a lot.

 Are you planning to use opam-health-check (or whatever the new name is :) to assess breakage when we first release the ppxlib support? (I don't remember if you already did this, apologies in this case.) If so, will you publish the results here?

**Comment by kit-ty-kate** [comment]
I was more planning to just use the regular opam-repository CI for this as many sub-libraries already constrain ppx_deriving to < 5.0, but since you asked I launched a special check. Here are the results:

Packages incompatible with the new API:
* visitors
* ppx_deriving_madcast
* js_of_ocaml-ppx_deriving_json < 3.5.0 (from 3.5.0 it doesn't use ppx_deriving anymore)
* ppx_deriving_rpc < 6.0.0 (from 6.0.0 it doesn't use ppx_deriving anymore)

Packages also incompatible (use ppx_tools directly and forgot to set the dependency explicitly):
* lens

Packages that fail because they use `seq` but ppx_deriving now use `stdlib-shims`, and those two have clashing interfaces (OCaml < 4.07 only):
* jwto
* gobba
* icalendar
* minicaml
* mirage-nat
* mmdb
* nbd
* owork
* protocol-9p-unix (< 0.12)
* tls (< 0.12)
* user-agent-parser

At the moment, I do not have the rights on this repo to make the release. Would it be possible to get it?

**Comment by gasche** [comment]
Thanks a lot for the checking. Comments:

- I don't think there is any problem with the packages that switched to ppxlib directly (ppx_deriving_rpc and jsoo-ppx_deriving_json)
- It looks like the 'lens' error is really easy to fix? if so, it would be nice to send a PR
- I would prefer to understand the problem with ppx_deriving_madcast and visitors, and possibly to fix them.
- the `seq` vs. `stdlib-shims` clash seems unfortunate, is there something we can do? (cc @thierry-martinez)

Regarding seq vs. stdlib-shims:
- If I am guessing correctly, the error comes from the fact that both libraries define a compilation unit called `Seq`, and there is a conflict if we try to compile both together within the same project.
- We don't make any usage of `Seq` in the ppx_deriving codebase, in particular not in `ppx_deriving_runtime`, so there is probably no link-time dependency on stdlib-shim's Seq. (In theory, with the right build instructions, we should be able to build a project that depends on both.) The error is probably rather an "incompatible cmi digest" error that comes out of compiling some module in an environment that sees both Seq modules, with the typer selecting the wrong one (the "good one" being the one that the project actually uses at link-time).
- What are the options to fix this problem? I see the following:
  + ppx_deriving could stop depending on stdlib-shims (... but I don't remember how much we rely on it nowadays)
  + stdlib-shims could provide an stdlib-shims-noseq subpackage that is compatible with seq
  + stdlib-shims could depend on the seq subpackage to provide a seq module, instead of providing a conflicting one
  + worse options, not worth considering as they increase dependencies: seq depending on stdlib-shims, or seq-using modules switching to stdlib-shims

**Comment by kit-ty-kate** [comment]
@gasche the issue with `seq` vs. `stdlib-shims` is that `ppxlib` depends on `stdlib-shims`. The `Seq` module seems to have been removed from `stdlib-shims` on master (in https://github.com/ocaml/stdlib-shims/pull/13). @dra27 is there a release of stdlib-shims planned?

**Comment by gasche** [comment]
Ah, actually I confused stdlib-shims and std_compat. Thanks for the clarification; if it's a dependency of ppxlib, there is nothing that ppx_deriving can do to fix the issue.

**Comment by dra27** [comment]
There is a release of stdlib-shims planned, yes!
