### ISSUE TITLE
[Help needed] Set printer to be a later-defined function

### ISSUE THREAD

**Issue by ljlin** [ocaml-ppx/ppx_deriving#266]
Hi,

This is a beginner question. Thanks for your help.

I want to set a printer to be a later-defined function. I tried using the `and` keywords like defining two functions that call each other, but OCaml says it's a syntax error. I don't know how to make type and function definitions able to refer to each other.
 
There is an MWE, and I want to set the `@print` for `x_type` to be `print_x`. I'd appreciate it if someone helps me with it.

```ocaml
type x_type =
  | X of y_type String.Map.t 
  [@printer print_x]
(*
File "mwe.ml", line 163, characters 12-19:
163 |   [@printer print_x]
                  ^^^^^^^
Error: Unbound value print_x
*)
  (* [@printer fun fmt _ -> Format.fprintf fmt "how to use print_x"] *)
and y_type = 
  | Y1 of int
  | Y2 of x_type
[@@deriving show]

let rec print_x fmt x = 
  match x with
  | X d ->
    let kvs = String.Map.to_alist d in
    Format.pp_print_list (fun fmt (key, data) -> 
      Format.fprintf fmt "%s : %a" key print_y data
    ) fmt kvs
and print_y fmt y = 
  match y with
  | Y1 n -> Format.fprintf fmt "%d" n
  | Y2 x -> print_x fmt x

```

**Comment by gasche** [comment]
In this case you would need recursion between values and types, which is not provided directly in OCaml. I see two approaches.

### Redeclaration

You can first define your types without the deriving directives, then define your human-written printers, and finally re-declare the types with deriving directives using the advanced `type t = <existing type> = <def>` construct.

```ocaml
module Predecl = struct
  type a = { x : x_type }
  and x_type =
    | X of (string * y_type) list
  and y_type =
    | Y1 of int
    | Y2 of a
end

open Predecl

let rec print_x fmt x =
  match x with
  | X kvs ->
    Format.pp_print_list (fun fmt (key, data) ->
      Format.fprintf fmt "%s : %a" key print_y data
    ) fmt kvs
and print_y fmt y =
  match y with
  | Y1 n -> Format.fprintf fmt "%d" n
  | Y2 {x} -> print_x fmt x

type a = Predecl.a = { x : x_type [@printer print_x] }
and x_type = Predecl.x_type =
  | X of (string * y_type) list
and y_type = Predecl.y_type =
  | Y1 of int
  | Y2 of a
[@@deriving show]
```

(Note: I had to change your example a bit because its fixed version would not type-cheeck, `print_x` as a printer was attached to the `(string * y_type) list` argument.)

### Recursive module

In the above approach, I need to define all user-defined printers before defining all derived printers. This does not let us call derived printers from user-defined printers.

A general approach to "I need recursion between ... and ..." is to use recursive modules. This lets us express user-defined printers that call derived printers (and still reference user-defined printers from the deriving annotations):

```ocaml
module rec M : sig
  type a = { x : x_type [@printer print_x] }
  and x_type =
    | X of (string * y_type) list
  and y_type =
    | Y1 of int
    | Y2 of a
  [@@deriving show]

  val print_x : Format.formatter -> x_type -> unit
end = struct
  type a = { x : x_type [@printer M.print_x] }
  and x_type =
    | X of (string * y_type) list
  and y_type =
    | Y1 of int
    | Y2 of a
  [@@deriving show]

  let rec print_x fmt x =
    match x with
    | X kvs ->
      Format.pp_print_list (fun fmt (key, data) ->
        Format.fprintf fmt "%s : %a" key print_y data
      ) fmt kvs
  and print_y fmt y =
    match y with
    | Y1 n -> Format.fprintf fmt "%d" n
    | Y2 a -> M.pp_a fmt a
end
```
